version: '3.8'

networks:
  swiftly-network:
    driver: bridge

services:
  swiftly-backend:
    build: .
    image: ktodacode/swiftly:latest
    ports:
      - "8080:8080"
    depends_on:
      - swiftly-database
    volumes:
      - ~/.m2:/root/.m2
      - ./pom.xml:/usr/src/app/pom.xml
      - ./logs:/var/log/swiftly-prod
    networks:
      - swiftly-network
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    env_file:
      - application-variables-prod.env

  swiftly-tests:
    build:
      context: .
      target: test
    image: ktodacode/swiftly:latest-test
    container_name: tests
    depends_on:
      - swiftly-database
    networks:
      - swiftly-network
    restart: no
    env_file:
      - application-variables-prod.env

  swiftly-database:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/sql/docker/init-db-docker-prod.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./data/db:/var/lib/postgresql/data
    networks:
      - swiftly-network
    restart: always
    env_file:
      - application-variables-prod.env